package it.polimi.ingsw.communication.common;

public enum MessageType {
    PINGPONG,
    LOGIN,
    LOBBIES,
    MAGE,
    CARD,
    CLOUDCARD,
    STUDENT,
    MOTHERNATURE,
    CHARACTERCHOICE,
    ERROR,
    LOGINERROR,
    MAGEERROR,
    NOERROR,
    CONNECTIONERROR,
    MYCARDLIST,
    CARDERROR,
    PLAYEDCARDLIST,
    TURN,
    MODEL,
    COIN,
    CHARACTERLIST,
    MOVESTUDENTERROR,
    MOVEMOTHERNATUREERROR,
    WIN
}
